# This file stores configurations for your Shopify app.

scopes = "write_products, read_all_orders, read_customers, read_inventory, read_orders, read_payment_terms, read_price_rules, read_products, read_shipping, read_returns, read_third_party_fulfillment_orders, read_order_edits"
